# Generated by Django 4.1.4 on 2022-12-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJOLOTLOL', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
