# Generated by Django 4.1.4 on 2022-12-30 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AJOLOTLOL', '0003_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('click_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ad_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JoinedLog',
            fields=[
                ('joined_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AJOLOTLOL.clicklog')),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('query_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='joinedlog',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AJOLOTLOL.querylog'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AJOLOTLOL.querylog'),
        ),
    ]
